### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by chrisrickenbacher** [danuk/k8s-sftp-gcs#1]
Nice solution @danuk, thanks for sharing! I tried this out but struggling with permissions. Do you know how I can give write access for the user? As I understand `/home/[user]/ftp` has no write access for the FTPS user.

**Comment by danuk** [comment]
Hello.
It works very well for me. Yes, write mode is supported.
I think you have problem with permissions on Google Cloud Storage.
This chart works very simple: we just mount GCS. If your bucket have correct permissions, it will work fine.

**Comment by fulhaq** [comment]
I am having the same issue here. I've deployed it a dozen times with different google auth keys - even one with Owner permission, yet get the same error.

**Comment by fulhaq** [comment]
After a decent amount of debugging, i realized the http call to GCS via gcsfuse to modify the contents of the gcsfuse folder was throwing a 403 (permission denied) error. The problem is with this export in configmap.yaml:

export GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcloud-key.json 

Unfortunately the export above is not available to the followed runuser gcefuse command within configmap.yaml, which mounts the GCS as the file system. Changing the configmap to below fixed my problem where i'm exporting the variable as well as mounting the drive in the same runuser session.


runuser -l {{ $user.user }} -c \
       {{- if $user.onlyDir }}
       'export GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcloud-key.json; gcsfuse --only-dir {{ $user.onlyDir }}  {{ $user.bucket }} /home/  {{ $user.user }}/ftp'
       {{ else }}
       'export GOOGLE_APPLICATION_CREDENTIALS=/credentials/gcloud-key.json; gcsfuse  {{ $user.bucket }} /home/{{ $user.user }}/ftp'
       {{- end }}

Hope this helps!

**Comment by chrisrickenbacher** [comment]
@fulhaq thanks a lot that's it. Works for me as well. My `configmap.yaml` data looks now like this and that works:
```
  gcs-mounts.sh: |-
    # !/bin/bash

    {{ range $item, $user := .Values.users -}}
      runuser -l {{ $user.user }} -c \
      {{- if $user.onlyDir }}
      'export GOOGLE_APPLICATION_CREDENTIALS="/credentials/gcloud-key.json"; gcsfuse --only-dir {{ $user.onlyDir }} {{ $user.bucket }} /home/ {{ $user.user }}/ftp'
      {{ else }}
      'export GOOGLE_APPLICATION_CREDENTIALS="/credentials/gcloud-key.json"; gcsfuse {{ $user.bucket }} /home/{{ $user.user }}/ftp'
      {{- end }}
    {{ end }}
```

**Comment by danuk** [comment]
Guys, thank you for your great work. I fixed it.
